#ifndef CATPLG_INITIALIZECMD_GLOBAL_H
#define CATPLG_INITIALIZECMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_INITIALIZECMD_LIB
# define CATPLG_INITIALIZECMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_INITIALIZECMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_INITIALIZECMD_GLOBAL_H
