#ifndef CATPLG_SETTRIGGERCMD_GLOBAL_H
#define CATPLG_SETTRIGGERCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_SETTRIGGERCMD_LIB
# define CATPLG_SETTRIGGERCMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_SETTRIGGERCMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_SETTRIGGERCMD_GLOBAL_H
