#ifndef CATPLG_CURVECHECKCMD_GLOBAL_H
#define CATPLG_CURVECHECKCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_CURVECHECKCMD_LIB
# define CATPLG_CURVECHECKCMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_CURVECHECKCMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_CURVECHECKCMD_GLOBAL_H
