#ifndef CATPLG_RESISTENCECMD_GLOBAL_H
#define CATPLG_RESISTENCECMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_RESISTENCECMD_LIB
# define CATPLG_RESISTENCECMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_RESISTENCECMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_RESISTENCECMD_GLOBAL_H
