#ifndef CATPLG_CLOSEPORTCMD_GLOBAL_H
#define CATPLG_CLOSEPORTCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_CLOSEPORTCMD_LIB
# define CATPLG_CLOSEPORTCMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_CLOSEPORTCMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_CLOSEPORTCMD_GLOBAL_H
