#ifndef CATPLG_CURRENTCMD_GLOBAL_H
#define CATPLG_CURRENTCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_CURRENTCMD_LIB
# define CATPLG_CURRENTCMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_CURRENTCMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_CURRENTCMD_GLOBAL_H
