#ifndef CATPLG_CHECKCMD_GLOBAL_H
#define CATPLG_CHECKCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_CHECKCMD_LIB
# define CATPLG_CHECKCMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_CHECKCMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_CHECKCMD_GLOBAL_H
