#ifndef CATPLG_VOLTAGECMD_GLOBAL_H
#define CATPLG_VOLTAGECMD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CATPLG_VOLTAGECMD_LIB
# define CATPLG_VOLTAGECMD_EXPORT Q_DECL_EXPORT
#else
# define CATPLG_VOLTAGECMD_EXPORT Q_DECL_IMPORT
#endif

#endif // CATPLG_VOLTAGECMD_GLOBAL_H
